name: Sample App Tests

on: push

jobs:
  sample_app_tests:
    name: "Run Tests Using Jest"
    runs-on: ubuntu-latest
    env:
      APP_WORKDIR: td5/scripts/sample-app
      NODE_VERSION: "20"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.APP_WORKDIR }}
        run: npm install

      - name: Run tests
        working-directory: ${{ env.APP_WORKDIR }}
        run: npm test
